/**
 * Purpose: Shared constants — safe for both server and client
 * Responsibility: Application-wide constant values
 */

export const APP_NAME = "निखरता रूप";
export const APP_NAME_EN = "Nikharta Roop";
export const APP_URL = process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000";

/** Deep Rose Pink — brand color */
export const BRAND_COLOR = "#C2185B";

/** HTTP status codes — used everywhere */
export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  NO_CONTENT: 204,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE: 422,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
} as const;

/** Machine-readable error codes — frontend uses these for conditional logic */
export const ERROR_CODES = {
  // Auth
  AUTH_MISSING_TOKEN: "AUTH_MISSING_TOKEN",
  AUTH_INVALID_TOKEN: "AUTH_INVALID_TOKEN",
  AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",
  AUTH_SESSION_INVALID: "AUTH_SESSION_INVALID",
  AUTH_SESSION_REVOKED: "AUTH_SESSION_REVOKED",
  AUTH_ACCOUNT_SUSPENDED: "AUTH_ACCOUNT_SUSPENDED",
  AUTH_OTP_INVALID: "AUTH_OTP_INVALID",
  AUTH_OTP_EXPIRED: "AUTH_OTP_EXPIRED",
  AUTH_OTP_MAX_ATTEMPTS: "AUTH_OTP_MAX_ATTEMPTS",
  AUTH_RATE_LIMITED: "AUTH_RATE_LIMITED",
  AUTH_LOGIN_LOCKED: "AUTH_LOGIN_LOCKED",
  AUTH_INVALID_CREDENTIALS: "AUTH_INVALID_CREDENTIALS",
  AUTH_EMAIL_EXISTS: "AUTH_EMAIL_EXISTS",
  AUTH_PHONE_EXISTS: "AUTH_PHONE_EXISTS",
  AUTH_GOOGLE_TOKEN_INVALID: "AUTH_GOOGLE_TOKEN_INVALID",
  AUTH_EMAIL_NOT_VERIFIED: "AUTH_EMAIL_NOT_VERIFIED",
  AUTH_MAGIC_LINK_INVALID: "AUTH_MAGIC_LINK_INVALID",
  AUTH_MAGIC_LINK_EXPIRED: "AUTH_MAGIC_LINK_EXPIRED",
  AUTH_REFRESH_REUSE: "AUTH_REFRESH_REUSE",
  AUTH_PASSWORD_RESET_INVALID: "AUTH_PASSWORD_RESET_INVALID",
  AUTH_PASSWORD_RESET_EXPIRED: "AUTH_PASSWORD_RESET_EXPIRED",
  AUTH_WRONG_PASSWORD: "AUTH_WRONG_PASSWORD",
  AUTH_EMAIL_TAKEN: "AUTH_EMAIL_TAKEN",
  AUTH_PHONE_TAKEN: "AUTH_PHONE_TAKEN",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  USER_DEACTIVATED: "USER_DEACTIVATED",
  USER_AVATAR_TOO_LARGE: "USER_AVATAR_TOO_LARGE",
  USER_AVATAR_INVALID_TYPE: "USER_AVATAR_INVALID_TYPE",

  // Validation
  VAL_INVALID_INPUT: "VAL_INVALID_INPUT",
  VAL_INVALID_PHONE: "VAL_INVALID_PHONE",
  VAL_INVALID_OTP: "VAL_INVALID_OTP",
  VAL_INVALID_EMAIL: "VAL_INVALID_EMAIL",

  // Resource
  RES_NOT_FOUND: "RES_NOT_FOUND",
  RES_CONFLICT: "RES_CONFLICT",

  // Permission
  PERM_DENIED: "PERM_DENIED",
  PERM_ADMIN_REQUIRED: "PERM_ADMIN_REQUIRED",
  PERM_STAFF_REQUIRED: "PERM_STAFF_REQUIRED",

  // Branch
  BRANCH_NOT_FOUND: "BRANCH_NOT_FOUND",
  BRANCH_ALREADY_INACTIVE: "BRANCH_ALREADY_INACTIVE",
  BRANCH_HOLIDAY_CONFLICT: "BRANCH_HOLIDAY_CONFLICT",
  BRANCH_HOLIDAY_NOT_FOUND: "BRANCH_HOLIDAY_NOT_FOUND",

  // Service Category
  SVC_CAT_NOT_FOUND: "SVC_CAT_NOT_FOUND",
  SVC_CAT_SLUG_EXISTS: "SVC_CAT_SLUG_EXISTS",
  SVC_CAT_ALREADY_INACTIVE: "SVC_CAT_ALREADY_INACTIVE",

  // Service
  SVC_NOT_FOUND: "SVC_NOT_FOUND",
  SVC_SLUG_EXISTS: "SVC_SLUG_EXISTS",
  SVC_ALREADY_INACTIVE: "SVC_ALREADY_INACTIVE",

  // Service Variant
  SVC_VAR_NOT_FOUND: "SVC_VAR_NOT_FOUND",
  SVC_VAR_ALREADY_INACTIVE: "SVC_VAR_ALREADY_INACTIVE",

  // Service Add-On
  SVC_ADDON_NOT_FOUND: "SVC_ADDON_NOT_FOUND",
  SVC_ADDON_ALREADY_INACTIVE: "SVC_ADDON_ALREADY_INACTIVE",

  // Staff
  STAFF_NOT_FOUND: "STAFF_NOT_FOUND",
  STAFF_ALREADY_DEACTIVATED: "STAFF_ALREADY_DEACTIVATED",
  STAFF_SERVICE_ALREADY_ASSIGNED: "STAFF_SERVICE_ALREADY_ASSIGNED",
  STAFF_LEAVE_CONFLICT: "STAFF_LEAVE_CONFLICT",
  STAFF_LEAVE_NOT_FOUND: "STAFF_LEAVE_NOT_FOUND",

  // Slot Availability
  SLOT_INVALID_DATE: "SLOT_INVALID_DATE",
  SLOT_BRANCH_CLOSED: "SLOT_BRANCH_CLOSED",
  SLOT_SERVICE_REQUIRED: "SLOT_SERVICE_REQUIRED",
  SLOT_NO_STAFF_AVAILABLE: "SLOT_NO_STAFF_AVAILABLE",

  // Booking
  BOOKING_NOT_FOUND: "BOOKING_NOT_FOUND",
  BOOKING_SLOT_UNAVAILABLE: "BOOKING_SLOT_UNAVAILABLE",
  BOOKING_INVALID_STATUS_TRANSITION: "BOOKING_INVALID_STATUS_TRANSITION",
  BOOKING_ALREADY_CANCELLED: "BOOKING_ALREADY_CANCELLED",
  BOOKING_CANNOT_CANCEL: "BOOKING_CANNOT_CANCEL",
  BOOKING_UNAUTHORIZED: "BOOKING_UNAUTHORIZED",
  BOOKING_OFFER_INVALID: "BOOKING_OFFER_INVALID",
  BOOKING_OFFER_NOT_APPLICABLE: "BOOKING_OFFER_NOT_APPLICABLE",
  BOOKING_OFFER_LIMIT_REACHED: "BOOKING_OFFER_LIMIT_REACHED",

  // Offer
  OFFER_NOT_FOUND: "OFFER_NOT_FOUND",
  OFFER_CODE_EXISTS: "OFFER_CODE_EXISTS",
  OFFER_EXPIRED: "OFFER_EXPIRED",
  OFFER_NOT_YET_ACTIVE: "OFFER_NOT_YET_ACTIVE",
  OFFER_USAGE_LIMIT_REACHED: "OFFER_USAGE_LIMIT_REACHED",
  OFFER_MIN_ORDER_NOT_MET: "OFFER_MIN_ORDER_NOT_MET",
  OFFER_NOT_APPLICABLE: "OFFER_NOT_APPLICABLE",
  OFFER_SERVICE_ALREADY_LINKED: "OFFER_SERVICE_ALREADY_LINKED",
  OFFER_SERVICE_LINK_NOT_FOUND: "OFFER_SERVICE_LINK_NOT_FOUND",
  OFFER_CODE_IMMUTABLE: "OFFER_CODE_IMMUTABLE",

  // Payment
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_ALREADY_SUCCESS: "PAYMENT_ALREADY_SUCCESS",
  PAYMENT_VERIFICATION_FAILED: "PAYMENT_VERIFICATION_FAILED",
  PAYMENT_BOOKING_MISMATCH: "PAYMENT_BOOKING_MISMATCH",
  REFUND_NOT_FOUND: "REFUND_NOT_FOUND",
  REFUND_ALREADY_PROCESSED: "REFUND_ALREADY_PROCESSED",
  REFUND_AMOUNT_EXCEEDS: "REFUND_AMOUNT_EXCEEDS",

  // Review
  REVIEW_NOT_FOUND: "REVIEW_NOT_FOUND",
  REVIEW_ALREADY_EXISTS: "REVIEW_ALREADY_EXISTS",
  REVIEW_BOOKING_NOT_COMPLETED: "REVIEW_BOOKING_NOT_COMPLETED",
  REVIEW_UNAUTHORIZED: "REVIEW_UNAUTHORIZED",
  REVIEW_BOOKING_NOT_OWNED: "REVIEW_BOOKING_NOT_OWNED",

  // Loyalty
  LOYALTY_INSUFFICIENT_BALANCE: "LOYALTY_INSUFFICIENT_BALANCE",
  LOYALTY_MIN_REDEEM_NOT_MET: "LOYALTY_MIN_REDEEM_NOT_MET",
  LOYALTY_INVALID_POINTS: "LOYALTY_INVALID_POINTS",

  // System
  SYS_INTERNAL: "SYS_INTERNAL",
  SYS_DATABASE: "SYS_DATABASE",
  SYS_SMS_FAILED: "SYS_SMS_FAILED",
  SYS_REDIS_ERROR: "SYS_REDIS_ERROR",
  SYS_EMAIL_FAILED: "SYS_EMAIL_FAILED",
} as const;
